// app/register/page.tsx
"use client";

import { Map } from "lucide-react";
import { Button } from "@/components/ui/button";
import "./card.css";

export default function Register() {
    const applicationVisibleDate = new Date("August 1, 2024");

    const openSmallCafeMap = () => {
        const smallCafeMapFile = "/floor-maps/small-cafe.pdf";
        window.open(smallCafeMapFile, "_blank");
    };

    const openLargeCafeMap = () => {
        const largeCafeMapFile = "/floor-maps/large-cafe.pdf";
        window.open(largeCafeMapFile, "_blank");
    };

    const openGymMap = () => {
        const gymMapFile = "/floor-maps/gym.pdf";
        window.open(gymMapFile, "_blank");
    };

    const openApplication = () => {
        const applicationFile = "/applications/2024_craft_show_application.pdf";
        window.open(applicationFile, "_blank");
    };

    return (
        <div className="px-4 md:px-8">
            <div className="mx-auto max-w-7xl">
                <div>
                    <h1 className="text-7xl font-semibold">Register</h1>
                    <p className="mt-4 text-xl">
                        Register to be a vendor at our Annual Craft Show!
                    </p>
                    <div className="mt-8 rounded-lg border border-green-700 bg-green-100 p-4">
                        <p className="text-green-900">
                            At this point, the only remaining spaces are{" "}
                            <strong>S-04</strong> and <strong>S-09</strong> in
                            the Small Cafe.
                        </p>
                    </div>

                    <div className="mt-6">
                        {new Date(Date.now()) >= applicationVisibleDate ? (
                            <>
                                <p>Fill out the 2024 application here!</p>
                                <Button
                                    size="lg"
                                    className="mt-2"
                                    onClick={openApplication}
                                >
                                    <span>2024 Application</span>
                                </Button>
                            </>
                        ) : (
                            <p>
                                The 2024 application will be available here on
                                August 1st at midnight.
                            </p>
                        )}
                    </div>
                </div>
                <div className="mt-12">
                    <h2 className="text-center text-5xl font-semibold">
                        2024 Booth Rates
                    </h2>
                    <div className="flex justify-center">
                        <div className="my-10 flex flex-col gap-10 text-xl lg:flex-row">
                            <div className="card">
                                <h3 className="text-center text-3xl font-semibold">
                                    Small Cafe
                                </h3>
                                <span className="-mt-3 h-[1px] w-full bg-gradient-to-r from-transparent via-black to-transparent"></span>
                                <div className="flex h-full flex-col justify-between">
                                    <div className="w-full">
                                        <div className="flex w-full flex-col gap-5">
                                            <div className="flex justify-between">
                                                <span>Regular Space</span>
                                                <span className="font-semibold">
                                                    $40.00
                                                </span>
                                            </div>
                                        </div>
                                    </div>

                                    <Button onClick={openSmallCafeMap}>
                                        <div className="flex items-center gap-2">
                                            <Map />
                                            <span>Small Cafe Map</span>
                                        </div>
                                    </Button>
                                </div>
                            </div>
                            <div className="card">
                                <h3 className="text-center text-3xl font-semibold">
                                    Large Cafe
                                </h3>
                                <span className="-mt-3 h-[1px] w-full bg-gradient-to-r from-transparent via-black to-transparent"></span>
                                <div className="flex h-full flex-col justify-between">
                                    <div className="w-full">
                                        <div className="flex w-full flex-col gap-5">
                                            <div className="flex justify-between">
                                                <span>Regular Space</span>
                                                <span className="font-semibold">
                                                    $55.00
                                                </span>
                                            </div>
                                            <div className="flex justify-between">
                                                <span>Corner Space</span>
                                                <span className="font-semibold">
                                                    $65.00
                                                </span>
                                            </div>
                                        </div>
                                    </div>

                                    <Button onClick={openLargeCafeMap}>
                                        <div className="flex items-center gap-2">
                                            <Map />
                                            <span>Large Cafe Map</span>
                                        </div>
                                    </Button>
                                </div>
                            </div>
                            <div className="card">
                                <h3 className="text-center text-3xl font-semibold">
                                    Gym
                                </h3>
                                <span className="-mt-3 h-[1px] w-full bg-gradient-to-r from-transparent via-black to-transparent"></span>
                                <div className="flex h-full flex-col justify-between">
                                    <div className="w-full">
                                        <div className="flex w-full flex-col gap-5">
                                            <div className="flex justify-between">
                                                <span>Regular Space</span>
                                                <span className="font-semibold">
                                                    $60.00
                                                </span>
                                            </div>
                                            <div className="flex justify-between">
                                                <span>Endcap Space</span>
                                                <span className="font-semibold">
                                                    $70.00
                                                </span>
                                            </div>
                                            <div className="flex justify-between">
                                                <span>Corner Space</span>
                                                <span className="font-semibold">
                                                    $85.00
                                                </span>
                                            </div>
                                        </div>
                                    </div>

                                    <Button onClick={openGymMap}>
                                        <div className="flex items-center gap-2">
                                            <Map />
                                            <span>Gym Map</span>
                                        </div>
                                    </Button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

// src/app/register/register.component.ts
import { Component } from '@angular/core';
import { Firestore, collection, collectionData, orderBy, query, where } from '@angular/fire/firestore';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent {

  vendorSpacesRef = collection(this.firestore, 'vendorSpaces');

  loading = true;
  availableGymSpaces: any[] = [];
  availableLargeCafeSpaces: any[] = [];
  availableSmallCafeSpaces: any[] = [];

  constructor(
    private firestore: Firestore
  ) {
    let availableSpacesQuery = query(this.vendorSpacesRef, 
      where('vendor', '==', null));
    let availableSpaces$ = collectionData(
      availableSpacesQuery,
      {idField: 'id'} // This allows us to access the document id
    );
    availableSpaces$.subscribe( spaces => {
      for (let space of spaces) {
        switch (space['location']) {
          case 'GYM':
            this.availableGymSpaces.push(space);
            break;
          case 'LARGE CAFE':
            this.availableLargeCafeSpaces.push(space);
            break;
          case 'SMALL CAFE':
            this.availableSmallCafeSpaces.push(space);
            break;
          default:
            console.log('Unknown space location: ' + space['location'], space)
        }
      }
      this.loading = false;
    });
  }

  openGymMap() {
    let gymMapFile = '/assets/floor-maps/gym.pdf';
    window.open(gymMapFile, '_blank');
  }

  openLargeCafeMap() {
    let largeCafeMapFile = '/assets/floor-maps/large-cafe.pdf';
    window.open(largeCafeMapFile, '_blank');
  }

  openSmallCafeMap() {
    let smallCafeMapFile = '/assets/floor-maps/small-cafe.pdf';
    window.open(smallCafeMapFile, '_blank');
  }

}

<div class="mx-2">
    <div class="col-12 md:col-10 m-auto mt-4">
        <div class="flex flex-column">
            <h2>2023 Booth Rates</h2>
            <div class="grid mb-2">
                <div class="col-12 md:col">
                    <div class="card h-30rem">
                        <div class="flex flex-column h-full justify-content-between">
                            <div class="text-4xl">
                                <div class="flex justify-content-center mb-5">
                                    <span class="font-bold text-center">Gym</span>
                                </div>
                                <div class="flex flex-column justify-content-between">
                                    <div class="flex flex-column gap-3">
                                        <div class="flex justify-content-between">
                                            <span>Regular Space</span>
                                            <span>$60.00</span>
                                        </div>
                                        <div class="flex justify-content-between">
                                            <span>Endcap Space</span>
                                            <span>$70.00</span>
                                        </div>
                                        <div class="flex justify-content-between">
                                            <span>Corner Space</span>
                                            <span>$85.00</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="flex justify-content-center">
                                <p-button styleClass="p-button-secondary" label="See floor map" icon="fa-solid fa-map" (onClick)="openGymMap()">
                                </p-button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 md:col">
                    <div class="card h-30rem">
                        <div class="flex flex-column h-full justify-content-between">
                            <div class="text-4xl">
                                <div class="flex justify-content-center mb-5">
                                    <span class="font-bold text-center">Large Cafe</span>
                                </div>
                                <div class="flex flex-column justify-content-between">
                                    <div class="flex flex-column gap-3">
                                        <div class="flex justify-content-between">
                                            <span>Regular Space</span>
                                            <span>$55.00</span>
                                        </div>
                                        <div class="flex justify-content-between">
                                            <span>Corner Space</span>
                                            <span>$65.00</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="flex justify-content-center">
                                <p-button styleClass="p-button-secondary" label="See floor map" icon="fa-solid fa-map" (onClick)="openLargeCafeMap()">
                                </p-button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 md:col">
                    <div class="card h-30rem">
                        <div class="flex flex-column h-full justify-content-between">
                            <div class="text-4xl">
                                <div class="flex justify-content-center mb-5">
                                    <span class="font-bold text-center">Small Cafe</span>
                                </div>
                                <div class="flex flex-column justify-content-between">
                                    <div class="flex flex-column gap-3">
                                        <div class="flex justify-content-between">
                                            <span>Regular Space</span>
                                            <span>$40.00</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="flex justify-content-center">
                                <p-button styleClass="p-button-secondary" label="See floor map" icon="fa-solid fa-map" (onClick)="openSmallCafeMap()">
                                </p-button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="flex flex-column mb-4">
                <h2>Available Spaces</h2>
                <!-- <div *ngIf="this.loading">
                    <p-progressSpinner></p-progressSpinner>
                </div>
                <div *ngIf="!this.loading">
                    <div class="flex flex-column mb-2">
                        <span class="font-bold">GYM</span>
                        <span *ngFor="let gymSpace of availableGymSpaces">
                            {{ gymSpace.name }}
                        </span>
                    </div>
                    <div class="flex flex-column mb-2">
                        <span class="font-bold">LARGE CAFE</span>
                        <span *ngFor="let largeCafeteriaSpace of availableLargeCafeSpaces">
                            {{ largeCafeteriaSpace.name }}
                        </span>
                    </div>
                    <div class="flex flex-column">
                        <span class="font-bold">SMALL CAFE</span>
                        <span *ngFor="let smallCafeteriaSpace of availableSmallCafeSpaces">
                            {{ smallCafeteriaSpace.name }}
                        </span>
                    </div>
                </div> -->
                <div class="card col-12">
                    <span class="text-2xl">🎉 We are completely booked for this season! 🎉</span>
                </div>
            </div>
        </div>
    </div>
</div>
